name = "Lie"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["Lie"]

[leanOptions]
pp.unicode.fun = true
autoImplicit = false

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.19.0"

[[lean_lib]]
name = "Lie"
